/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.apollo.demo.simplekafka.model;

@org.apache.avro.specific.AvroGenerated
public enum PageEventType implements org.apache.avro.generic.GenericEnumSymbol<PageEventType> {
    AMAZING_USER, NORMAL_USER, NOT_A_KEEPER;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PageEventType\",\"namespace\":\"com.apollo.demo.simplekafka.model\",\"symbols\":[\"AMAZING_USER\",\"NORMAL_USER\",\"NOT_A_KEEPER\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
