spring:
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        pageViewEventSupplier-out-0:
          useNativeEncoding: true
          destination: avro-page-events
          content-type: application/*+avro
          producer-properties:
            keySerde: io.confluent.kafka.serializers.KafkaAvroSerializer
            valueSerde: io.confluent.kafka.serializers.KafkaAvroSerializer
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true